#!/usr/bin/env python3
"""joblist — find the remote jobs that will actually hire you, and pay.

Usage:
    py main.py                  fetch, filter, score, write today's digest
    py main.py --dry-run        run everything, persist nothing
    py main.py --no-llm         deterministic filters only; no API key needed
    py main.py --explain        print the funnel and every rejection reason
    py main.py --since 72h      override the watermark
    py main.py --json           also print results as JSON on stdout
    py main.py --fast           score with the cheaper model

Progress goes to stderr, results to stdout, the digest to data/digest/.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import UTC, datetime, timedelta

import config
import digest as digest_mod
import filters
import targeting
from sources.himalayas import Himalayas
from store import Store


def parse_since(text: str) -> timedelta:
    match = re.fullmatch(r"(\d+)\s*([hdw])", text.strip(), re.I)
    if not match:
        raise argparse.ArgumentTypeError("use forms like 24h, 7d, 2w")
    n, unit = int(match.group(1)), match.group(2).lower()
    return {"h": timedelta(hours=n), "d": timedelta(days=n), "w": timedelta(weeks=n)}[unit]


def load_api_key() -> str:
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if key:
        return key
    if os.path.exists(".env"):
        with open(".env", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line.startswith("ANTHROPIC_API_KEY="):
                    return line.split("=", 1)[1].strip().strip("\"'")
    return ""


def _force_utf8() -> None:
    """Windows consoles default to cp1252 and raise on the digest's symbols."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure:
            reconfigure(encoding="utf-8", errors="replace")


def log(message: str) -> None:
    print(message, file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-llm", action="store_true")
    parser.add_argument("--explain", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--fast", action="store_true")
    parser.add_argument("--since", type=parse_since, default=None)
    parser.add_argument("--profile", default=config.PROFILE_PATH)
    parser.add_argument("-h", "--help", action="store_true")
    args = parser.parse_args()
    _force_utf8()

    if args.help:
        print(__doc__)
        return 0

    try:
        profile = targeting.load(args.profile)
    except targeting.ProfileError as exc:
        log("[error] " + str(exc))
        return 1

    if not profile.resume and not args.no_llm:
        log(
            f"[warn] {profile.resume_path} is empty or missing — scoring will be weak.\n"
            "       For this repo it is generated by: cd data/cv && node build.js"
        )

    started_at = datetime.now(UTC)
    store = Store()
    run_id = store.start_run()
    since = started_at - args.since if args.since else store.since()
    log(f"[run] profile={profile.name} since={since:%Y-%m-%d %H:%M}Z")

    funnel = filters.Funnel()
    source = Himalayas()
    fresh: list[filters.Verdict] = []

    try:
        for job in source.fetch(since):
            funnel.fetched += 1
            if store.seen(job.key):
                funnel.seen_skipped += 1
                continue
            verdict = filters.evaluate(job, profile, started_at)
            funnel.add(verdict)
            if verdict.passed:
                fresh.append(verdict)
    except Exception as exc:  # noqa: BLE001 - the run record must capture why
        store.finish_run(run_id, ok=False, fetched=funnel.fetched, error=str(exc))
        store.close()
        log(f"[error] fetch failed: {exc}")
        return 1

    log(f"[run] {funnel.line()} ({source.pages_fetched} pages)")
    if source.hit_page_cap:
        log(
            f"[warn] stopped at the {config.HIMALAYAS_MAX_PAGES}-page cap before reaching {since:%Y-%m-%d %H:%M}Z — "
            "older jobs in this window were NOT seen. Raise HIMALAYAS_MAX_PAGES "
            "or run more often."
        )

    if args.explain:
        for verdict in funnel.rejects:
            log(f"  [{verdict.rejected_by}] {verdict.job.title[:52]} — {verdict.reason}")

    results: list[dict] = []
    model_used = "none"
    if fresh and not args.no_llm:
        api_key = load_api_key()
        if not api_key:
            log("[error] no ANTHROPIC_API_KEY (env or .env). Use --no-llm to skip scoring.")
            store.finish_run(run_id, ok=False, fetched=funnel.fetched, error="no api key")
            store.close()
            return 1
        import scorer

        model_used = config.FAST_MODEL if args.fast else config.SCORING_MODEL
        results = scorer.score(fresh, profile, api_key, model=model_used)
    else:
        results = [
            {"i": i, "score": None, "verdict": "unscored", "why": "",
             "matched_skills": [], "concerns": [], "cv_variant": "engineering"}
            for i in range(len(fresh))
        ]

    # scorer.score() pads to len(fresh), so a length mismatch is a real bug.
    pairs = list(zip(fresh, results, strict=True))

    text = digest_mod.render(funnel, pairs, profile, model_used, started_at, no_llm=args.no_llm)

    if args.dry_run:
        log("[run] dry-run: nothing persisted")
        print(text)
    else:
        path = digest_mod.write(text, started_at)
        log(f"[run] digest -> {path}")
        for verdict, result in pairs:
            store.record_job(
                verdict.job, run_id, verdict.salary_signal,
                score=result.get("score"), verdict=result.get("verdict"),
                why=result.get("why"), cv_variant=result.get("cv_variant"),
            )
        for verdict in funnel.rejects:
            store.record_reject(verdict, run_id)
        store.commit()
        store.finish_run(
            run_id, ok=True, fetched=funnel.fetched, scored=len(pairs),
            funnel=funnel.line(), model=model_used,
        )

    if args.json:
        print(json.dumps(
            [
                {
                    "uid": v.job.key, "title": v.job.title, "company": v.job.company,
                    "url": v.job.url, "regions": list(v.job.location_restrictions),
                    "salary_signal": v.salary_signal, **r,
                }
                for v, r in pairs
            ],
            indent=2,
        ))

    store.close()
    above = sum(1 for _, r in pairs if (r.get("score") or 0) >= profile.display_threshold)
    log(f"[run] done — {len(pairs)} scored, {above} above {profile.display_threshold}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
