#!/usr/bin/env python3
"""joblist — find the remote jobs that will actually hire you, and pay.

Usage:
    py main.py                  fetch, filter, score, write today's digest
    py main.py --dry-run        run everything, persist nothing
    py main.py --no-llm         deterministic filters only; no API key needed
    py main.py --explain        print the funnel and every rejection reason
    py main.py --since 72h      override the watermark
    py main.py --source onlinejobs   run one source only
    py main.py --rescore        re-evaluate already-seen jobs in the window
    py main.py --json           also print results as JSON on stdout
    py main.py --fast           score with the cheaper model
    py main.py --no-cover       skip auto-drafting letters for the high scorers

Progress goes to stderr, results to stdout, the digest to data/digest/.
Cover letter drafts go to data/covers/, one per high-scoring job.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import UTC, datetime, timedelta

import blockers as blockers_mod
import config
import cover
import digest as digest_mod
import filters
import targeting
from sources.himalayas import Himalayas
from sources.onlinejobs import OnlineJobs
from store import Store


def parse_since(text: str) -> timedelta:
    match = re.fullmatch(r"(\d+)\s*([hdw])", text.strip(), re.I)
    if not match:
        raise argparse.ArgumentTypeError("use forms like 24h, 7d, 2w")
    n, unit = int(match.group(1)), match.group(2).lower()
    return {"h": timedelta(hours=n), "d": timedelta(days=n), "w": timedelta(weeks=n)}[unit]


def load_api_key() -> str:
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if key:
        return key
    if os.path.exists(".env"):
        with open(".env", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line.startswith("ANTHROPIC_API_KEY="):
                    return line.split("=", 1)[1].strip().strip("\"'")
    return ""


def _force_utf8() -> None:
    """Windows consoles default to cp1252 and raise on the digest's symbols."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure:
            reconfigure(encoding="utf-8", errors="replace")


def log(message: str) -> None:
    print(message, file=sys.stderr)


def _run_summary(pairs, profile, blocked: int) -> str:
    """The closing line, per board.

    `profile.display_threshold` still exists as the value `boards.defaults`
    falls back to, and is deliberately not read here: a pooled "above
    threshold" count would blend one board's zero threshold into another's
    non-zero one, which is the exact number this rework exists to stop
    producing. Ask each board what its own bar is.
    """
    parts = []
    for board_name in sorted({v.job.source for v, _ in pairs}):
        board = profile.board(board_name)
        board_results = [r for v, r in pairs if v.job.source == board_name]
        above = sum(1 for r in board_results if (r.get("score") or 0) >= board.display_threshold)
        parts.append(f"{board_name} {above}/{len(board_results)} above {board.display_threshold}")
    breakdown = " (" + ", ".join(parts) + ")" if parts else ""
    note = f", {blocked} blocked" if blocked else ""
    return f"[run] done — {len(pairs)} scored{breakdown}{note}"


def main() -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-llm", action="store_true")
    parser.add_argument("--explain", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--fast", action="store_true")
    parser.add_argument("--no-cover", action="store_true",
                        help="skip auto-drafting cover letters for high scorers")
    parser.add_argument("--since", type=parse_since, default=None)
    parser.add_argument("--source", default=None,
                        help="run only this source (himalayas | onlinejobs)")
    parser.add_argument("--rescore", action="store_true",
                        help="re-evaluate jobs already marked seen (costs tokens)")
    parser.add_argument("--profile", default=config.PROFILE_PATH)
    parser.add_argument("-h", "--help", action="store_true")
    args = parser.parse_args()
    _force_utf8()

    if args.help:
        print(__doc__)
        return 0

    try:
        profile = targeting.load(args.profile)
    except targeting.ProfileError as exc:
        log("[error] " + str(exc))
        return 1

    if not profile.resume and not args.no_llm:
        log(
            f"[warn] {profile.resume_path} is empty or missing — scoring will be weak.\n"
            "       For this repo it is generated by: cd data/cv && node build.js"
        )

    started_at = datetime.now(UTC)
    store = Store()
    run_id = store.start_run()
    since = started_at - args.since if args.since else store.since()
    log(f"[run] profile={profile.name} since={since:%Y-%m-%d %H:%M}Z")

    funnel = filters.Funnel()
    fresh: list[filters.Verdict] = []

    sources = [(Himalayas(), config.HIMALAYAS_MAX_PAGES, "HIMALAYAS_MAX_PAGES"),
               (OnlineJobs(), config.ONLINEJOBS_MAX_PAGES, "ONLINEJOBS_MAX_PAGES")]
    by_name = {s[0].name: s[0] for s in sources}
    if args.source:
        sources = [s for s in sources if s[0].name == args.source]
        if not sources:
            log(f"[error] no source named {args.source!r}")
            store.close()
            return 1

    # Boards are isolated, so every active source must declare its own policy.
    # Checked here, before a single request goes out, because discovering it
    # after a full fetch wastes the crawl and the operator's time.
    try:
        profile.require_boards([s[0].name for s in sources])
    except targeting.ProfileError as exc:
        log(f"[error] {exc}")
        store.close()
        return 1

    # Per-source isolation, deliberately. onlinejobs is scraped markup with no
    # contract behind it, so a class rename upstream is a matter of when. One
    # source dying must not throw away the other's results — the run only fails
    # if every source failed.
    failures: list[str] = []
    for source, max_pages, setting in sources:
        before = funnel.fetched
        try:
            for job in source.fetch(since):
                funnel.fetched += 1
                if not args.rescore and store.seen(job.key):
                    funnel.seen_skipped += 1
                    continue
                verdict = filters.evaluate(job, profile, started_at, source)
                funnel.add(verdict)
                if verdict.passed:
                    fresh.append(verdict)
        except Exception as exc:  # noqa: BLE001 - the run record must capture why
            failures.append(f"{source.name}: {exc}")
            log(f"[warn] {source.name} failed, continuing: {exc}")
            continue

        log(f"[run] {source.name}: {funnel.fetched - before} fetched "
            f"({source.pages_fetched} pages)")
        if source.hit_page_cap:
            log(
                f"[warn] {source.name} stopped at the {max_pages}-page cap before "
                f"reaching {since:%Y-%m-%d %H:%M}Z — older jobs in this window were "
                f"NOT seen. Raise {setting} or run more often."
            )

    if failures and len(failures) == len(sources):
        store.finish_run(run_id, ok=False, fetched=funnel.fetched, error="; ".join(failures))
        store.close()
        log("[error] every source failed: " + "; ".join(failures))
        return 1

    log(f"[run] {funnel.line()}")

    # Some sources only publish a teaser in their listing feed. Fetch the full
    # advert for survivors ONLY -- after the funnel, before scoring. Doing it at
    # fetch time would pay a request for every listing the salary floor throws
    # away, and skipping it entirely means both the scorer and
    # eligibility_sentences() judge a job on a few hundred truncated characters.
    hydratable = [v for v in fresh if hasattr(by_name.get(v.job.source), "hydrate")]
    if hydratable:
        cap = config.ONLINEJOBS_MAX_HYDRATE
        if len(hydratable) > cap:
            log(f"[warn] {len(hydratable)} survivors need full text but the cap is {cap}; "
                f"the remainder are scored on their teaser only")
            hydratable = hydratable[:cap]
        log(f"[run] fetching full text for {len(hydratable)} survivor(s)")
        for n, verdict in enumerate(hydratable, 1):
            source = by_name[verdict.job.source]
            full = source.hydrate(verdict.job)
            if full is not verdict.job:
                verdict.job = full
                # Hiring restrictions live in the boilerplate at the BOTTOM of
                # an ad, so they only become visible now. Recompute just this;
                # re-running the whole funnel here could retroactively reject a
                # job the counted funnel already passed.
                verdict.eligibility_notes = filters.eligibility_sentences(full.description)
            if n % 20 == 0:
                log(f"[run]   {n}/{len(hydratable)}")

    if args.explain:
        for verdict in funnel.rejects:
            log(f"  [{verdict.rejected_by}] {verdict.job.title[:52]} — {verdict.reason}")

    results: list[dict] = []
    model_used = "none"
    # Bound here rather than inside the scoring branch: auto-drafting reads it
    # further down, and an empty `fresh` would otherwise leave it undefined.
    api_key = ""
    if fresh and not args.no_llm:
        api_key = load_api_key()
        if not api_key:
            log("[error] no ANTHROPIC_API_KEY (env or .env). Use --no-llm to skip scoring.")
            store.finish_run(run_id, ok=False, fetched=funnel.fetched, error="no api key")
            store.close()
            return 1
        import scorer

        model_used = config.FAST_MODEL if args.fast else config.SCORING_MODEL
        results = scorer.score(fresh, profile, api_key, model=model_used)
    else:
        results = [
            {"i": i, "score": None, "verdict": "unscored", "why": "",
             "matched_skills": [], "concerns": [], "cv_variant": "engineering"}
            for i in range(len(fresh))
        ]

    # Intersect what each posting asked for with what this candidate cannot
    # supply, and dock the score for the mandatory ones. Deterministic and
    # local -- see blockers.py for why it is not the model's job.
    results = blockers_mod.apply(results, profile)
    blocked = sum(1 for r in results if r.get("blockers"))

    # scorer.score() pads to len(fresh), so a length mismatch is a real bug.
    pairs = list(zip(fresh, results, strict=True))

    # Draft letters for the high scorers BEFORE the digest renders, so the
    # digest can point at them. Not behind an opt-in flag: the whole point is
    # that the letter is already waiting when the digest is opened. Cost is
    # bounded by each board's draft_at plus COVER_MAX_PER_RUN. Skipped on
    # --dry-run, which persists nothing, and on --no-llm, where nothing scored.
    if pairs and api_key and not args.dry_run and not args.no_llm and not args.no_cover:
        drafted = cover.auto_draft(pairs, profile, api_key, log=log)
        if drafted:
            log(f"[run] {drafted} cover letter draft(s) in {config.COVER_DIR}/")

    text = digest_mod.render(funnel, pairs, profile, model_used, started_at, no_llm=args.no_llm)

    if args.dry_run:
        log("[run] dry-run: nothing persisted")
        print(text)
    else:
        path = digest_mod.write(text, started_at)
        log(f"[run] digest -> {path}")
        for verdict, result in pairs:
            store.record_job(
                verdict.job, run_id, verdict.salary_signal,
                score=result.get("score"), verdict=result.get("verdict"),
                why=result.get("why"), cv_variant=result.get("cv_variant"),
                score_raw=result.get("score_raw"), blockers=result.get("blockers"),
                requirements=result.get("requirements"),
            )
        for verdict in funnel.rejects:
            store.record_reject(verdict, run_id)
        store.commit()
        store.finish_run(
            run_id, ok=True, fetched=funnel.fetched, scored=len(pairs),
            funnel=funnel.line(), model=model_used,
        )

    if args.json:
        print(json.dumps(
            [
                {
                    "uid": v.job.key, "title": v.job.title, "company": v.job.company,
                    "url": v.job.url, "regions": list(v.job.location_restrictions),
                    "salary_signal": v.salary_signal, **r,
                }
                for v, r in pairs
            ],
            indent=2,
        ))

    store.close()
    log(_run_summary(pairs, profile, blocked))
    if blocked:
        log("[run] 'blocked' = a mandatory ask you flagged in deliverables.cannot_provide. "
            "See `py report.py`.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
